site_name: Carmel Wiki
site_url: https://ljx2013.github.io/carmel-wiki/
repo_url: https://github.com/ljx2013/carmel-wiki
repo_name: GitHub

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    # 不再使用 content.mathjax
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式

nav:
  - 首页: index.md
  - 数学:
    - 数学符号: 数学 Math/数学符号 Math symbols.md
    - 集合: 数学 Math/集合 set.md
    - 模意义下的数和运算:
      - 取模: 模意义下的数和运算/取模 mod.md
      - 裴蜀定理: 模意义下的数和运算/裴蜀定理 Bezout identity.md
      - 中国剩余定理: 模意义下的数和运算/中国剩余定理 CRT.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
      inline_syntax: dollar

# 加载官方 MathJax 脚本即可，不需要任何自定义 JS
extra_javascript:
  # 先加载你的 MathJax 配置
  - js/mathjax-config.js
  # 再加载 MathJax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/theme-color.css
  - css/palette-transition.css
